
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/run/initialize
/process/list
/gun/particle neutron
/gun/energy 2.5 MeV
#==================== Analysis ========================
/analysis/setFileName MgF2
/analysis/h1/set 0  100  0. 100. none	#nb colli >57keV
/analysis/h1/set 1  100  0. 100. cm	#track len >57keV
/analysis/h1/set 2  100  0. 5. us	#time of flight >57keV
/analysis/h1/set 3  100  0. 1000. none	#nb colli <57keV
/analysis/h1/set 4  100  0. 500. cm	#track len <57keV
/analysis/h1/set 5  100  0. 1000. us	#time of flight <57keV
/analysis/h1/set 6  3000  0. 3 MeV	#step energy of the primary neutron
/analysis/h1/set 7  3000  0. 3 MeV #neutron entering moderator1
/analysis/h1/set 8  3000  0. 3 MeV #neutron entering moderator2
/analysis/h1/set 9  3000  0. 3 MeV #neutron entering energy filter
/analysis/h1/set 10  3000  0. 3 MeV #neutron entering Li thermal neutron absorber
/analysis/h1/set 11  3000  0. 3 MeV #neutron entering feedthrough port
/analysis/h1/set 12  3000  0. 3 MeV #neutron entering gaseous argon buffer
/analysis/h1/set 13  3000  0. 3 MeV #neutron entering liquid argon pool
/analysis/h2/set 0 100 -50 50 cm none linear 100 -50 50 cm none linear #neutron capture position in 1st moderator y:x (top view)
/analysis/h2/set 1 100 -50 50 cm none linear 100 550 650 cm none linear #neutron capture position in 1st moderator z:x (side view)
/analysis/h2/set 2 100 -50 50 cm none linear 100 -50 50 cm none linear #neutron capture position in 2nd moderator y:x (top view)
/analysis/h2/set 3 100 -50 50 cm none linear 100 520 580 cm none linear #neutron capture position in 2nd moderatorz:x (side view)
/analysis/h2/set 4 50 -15 15 cm none linear 50 -15 15 cm none linear #neutron capture position in filter y:x (top view)
/analysis/h2/set 5 50 -15 15 cm none linear 100 480 550 cm none linear #neutron capture position in filter z:x (side view)
/analysis/h2/set 6 100 -30 30 m none linear 100 -8 8 m none linear #neutron capture position in LAr TPC y:x (top view)
/analysis/h2/set 7 100 -30 30 m none linear 100 -8 8 m none linear #neutron capture position in LAr TPC z:x (side view)
#=======================================================
/ddsource/det/SetModerator1Material mat_Fe
/ddsource/det/setModerator1Height 25 cm
/primary/updateGunPosition

/run/printProgress 1000
#
/run/beamOn 10000


